version: "3"

services:
  cachet:
    build:
      context: .
      args:
        - cachet_ver=master
    ports:
      - 80:8000
    environment:
      - DB_DRIVER=sqlite
      - APP_KEY=${APP_KEY:-null}
      - APP_LOG=errorlog
      - DEBUG=false
    volumes:
      - cachetdb:/var/www/html/database
    restart: on-failure

volumes:
  cachetdb:
