postgres:
  image: postgres:9.4.4
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
cachet:
  build: .
  ports:
    - 80:8000
  links:
    - postgres:postgres
  environment:
    - DB_DRIVER=pgsql
    - DB_HOST=postgres
    - DB_DATABASE=postgres
    - DB_USERNAME=postgres
    - DB_PASSWORD=postgres
