version: "2"

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./docker/nginx-site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:8000
    links:
      - cachet
    volumes_from:
      - cachet
    depends_on:
      - cachet
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  cachet:
    build: .
    expose:
      - 9000
    links:
      - postgres:postgres
    environment:
      - DB_DRIVER=pgsql
      - DB_HOST=postgres
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    volumes:
      - /var/www
    depends_on:
      - postgres
