apiVersion: v1
kind: DeploymentConfig
metadata:
  name: cachet
  labels:
    app: cachet
  annotations:
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources:
  triggers:
    -
      type: ConfigChange
  replicas: 1
  test: false
  selector:
    app: cachet
    deploymentconfig: cachet
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cachet
        deploymentconfig: cachet
      annotations:
    spec:
      containers:
        -
          name: cachet
          image: cachethq/docker:2.3.10
          ports:
            -
              containerPort: 80
              protocol: TCP
          env:
            -
              name: DB_DATABASE
              value: cachethd
            -
              name: DB_DRIVER
              value: pgsql
            -
              name: DB_HOST
              value: crunchy-postgres
            -
              name: DB_PASSWORD
              value: cachethd!
            -
              name: DB_USERNAME
              value: cachethd
            -
              name: MAIL_DRIVER
              value: smtp
            -
              name: MAIL_HOST
              value: mailout.com
            -
              name: MAIL_PORT
              value: '25'
            -
              name: APP_ENV
              value: nonProd
            -
              name: APP_DEBUG
              value: 'false'
          resources:
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        runAsUser: 0
status: